In [1]:
import pandas as pd
import os
import numpy as np
import string
import re
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [2]:
# path of training data
train_path = 'train.xlsx'

# path of testing data
test_path = 'test.xlsx'

In [3]:
# show the first 5 rows of the training data
train_df = pd.read_excel(train_path)
print(train_df.head())

# show the first 5 rows of the testing data
test_df = pd.read_excel(test_path)
print(test_df.head())

                                              report class_name  class_index
0  "For any event on my bookmarked projects" opti...    Backend            1
1           Switch to using full l10n id's in urlbar   Frontend            2
2  Consider removing hasicon property to simplify...   Frontend            2
3  Method to obtain current URL from WebBrowserEd...   Frontend            2
4              Fix: migration fails in MS SQL-Server    Backend            1
                                              report class_name  class_index
0  REST API - ability to list sub projects for a ...    Backend            1
1  support selective text on right if set in GNOM...   Frontend            2
2  [meta][userstory] Ship v1 of Pre-populated top...   Frontend            2
3  Include updated_on and passwd_changed_on colum...    Backend            1
4    Problem with email integration to MS Office 365    Backend            1


In [4]:
def convert_lower_case(data):
    return str(data).lower()

In [5]:
def remove_punctuation(data):
    symbols = "!\"#$%&()*+-./:;<=>?@[\]^_`{|}~\n"
    for i in symbols:
        data = np.char.replace(data, i, ' ')

    return str(data)


In [6]:
def remove_apostrophe(data):
    return np.char.replace(data, "'", "")

In [7]:
def remove_numbers(data):
    return re.sub(r'\d+', '', str(data))

In [8]:
def remove_single_characters(tokens):
    new_text = ""
    for w in tokens:
        if len(w) > 1:
            new_text = new_text + " " + w
    return new_text

In [9]:
def lemmatization(data):
    lemmatizer = WordNetLemmatizer()
    tokens = word_tokenize(data)
    data = remove_single_characters(tokens)
    lemmatized_output = ' '.join([lemmatizer.lemmatize(word) for word in tokens])
    return lemmatized_output

In [10]:
def preprocess(data):
    data = convert_lower_case(data)
    data = remove_punctuation(data)
    data = remove_apostrophe(data)
    data = remove_numbers(data)
    data = lemmatization(data)
    return data

In [11]:
# print the first report of the training data
print(train_df['report'][0])


"For any event on my bookmarked projects" option not sending notifications for non-member bookmarked projects


In [12]:
# preprocess the first report of the training data
print(preprocess(train_df['report'][0]))


for any event on my bookmarked project option not sending notification for non member bookmarked project


In [14]:
import pandas as pd

# Assuming train_df is your DataFrame containing training data
# Assuming train_df has columns 'id', 'report', and 'class_name'

# Initialize counter
counter = 1

# Iterate over each row in the DataFrame
with open('preprocessed_train_data.csv', 'w', encoding='utf-8') as f:
    f.write('bug_description , class_name\n')  # Write header

    for _, row in train_df.iterrows():
        # Preprocess the 'report' column
        preprocessed_report = preprocess(row['report'])

        # Write data to the file with incremented counter
        f.write(f"{preprocessed_report},{row['class_name']}\n")

# Print the first preprocessed report
print(train_df['report'][0])


"For any event on my bookmarked projects" option not sending notifications for non-member bookmarked projects


In [15]:
# FOR TESTING DATA

# Iterate over each row in the DataFrame
with open('preprocessed_test_data.csv', 'w', encoding='utf-8') as f:
    f.write('bug_description , class_name\n')  # Write header

    for _, row in test_df.iterrows():
        # Preprocess the 'report' column
        preprocessed_report = preprocess(row['report'])

        # Write data to the file with incremented counter
        f.write(f"{preprocessed_report},{row['class_name']}\n")

# Print the first preprocessed report
print(test_df['report'][0])


REST API - ability to list sub projects for a project


In [16]:
# Open the preprocessed data file for reading
with open('preprocessed_train_data.csv', 'r', encoding='utf-8') as f:
    # Open the new file for writing preprocessed data with 2 columns
    with open('preprocessed_train_data2.csv', 'w', encoding='utf-8') as f_out:
        # Iterate over each line in the file
        for i, line in enumerate(f):
            # Skip the header
            if i == 0:
                continue
            
            # Split the line into columns based on comma delimiter
            columns = line.strip().split(',')
            
            # Check the number of columns
            if len(columns) == 2:
                # Get the preprocessed report and class name
                preprocessed_report = columns[0]
                class_name = columns[1]
                
                # Write the preprocessed report and class name to the new file
                f_out.write(f"{preprocessed_report},{class_name}\n")
            else:
                # Skip the line if it doesn't have exactly 2 columns
                continue


In [17]:
# FOR TESTING DATA

# Open the preprocessed data file for reading
with open('preprocessed_test_data.csv', 'r', encoding='utf-8') as f:
    # Open the new file for writing preprocessed data with 2 columns
    with open('preprocessed_test_data2.csv', 'w', encoding='utf-8') as f_out:
        # Iterate over each line in the file
        for i, line in enumerate(f):
            # Skip the header
            if i == 0:
                continue
            
            # Split the line into columns based on comma delimiter
            columns = line.strip().split(',')
            
            # Check the number of columns
            if len(columns) == 2:
                # Get the preprocessed report and class name
                preprocessed_report = columns[0]
                class_name = columns[1]
                
                # Write the preprocessed report and class name to the new file
                f_out.write(f"{preprocessed_report},{class_name}\n")
            else:
                # Skip the line if it doesn't have exactly 2 columns
                continue


In [13]:
# read the preprocessed data from the new file
preprocessed_train_df = pd.read_csv('preprocessed_train_data2.csv')

# show the first 5 rows of the preprocessed training data
print(preprocessed_train_df.head())

                                     bug_description class_name
0  for any event on my bookmarked project option ...    Backend
1               switch to using full ln id in urlbar   Frontend
2  consider removing hasicon property to simplify...   Frontend
3  method to obtain current url from webbrowsered...   Frontend
4                fix migration fails in m sql server    Backend


In [14]:
# read the preprocessed data from the new file
preprocessed_test_df = pd.read_csv('preprocessed_test_data2.csv')

# show the first 5 rows of the preprocessed training data
print(preprocessed_test_df.head())

                                     bug_description class_name
0  rest api ability to list sub project for a pro...    Backend
1  support selective text on right if set in gnom...   Frontend
2  meta userstory ship v of pre populated topsite...   Frontend
3  include updated on and passwd changed on colum...    Backend
4         problem with email integration to m office    Backend


## Feature Exraction

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Replace NaN values with an empty string
preprocessed_train_df['bug_description'].fillna('', inplace=True)

# Initialize the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the preprocessed data
X_train = vectorizer.fit_transform(preprocessed_train_df['bug_description'])

# Print the shape of the transformed data
print(X_train.shape)


(13866, 7663)


In [16]:
# print the vector representation of the first report
print(X_train[0])

  (0, 3991)	0.2538660078657135
  (0, 4326)	0.22188781122260037
  (0, 4360)	0.16200943672815057
  (0, 5895)	0.26840990743892756
  (0, 4344)	0.12359962887671232
  (0, 4562)	0.18653498271477986
  (0, 5086)	0.3360730020928219
  (0, 692)	0.6032988290912195
  (0, 4234)	0.2431528345726809
  (0, 4482)	0.13533242661691539
  (0, 2189)	0.24482610182777964
  (0, 299)	0.25719129168101634
  (0, 2527)	0.2398225552777558


In [17]:
# Print the number of unique class_name in the training data
print(preprocessed_train_df['class_name'].nunique())

# print their unique values
print(preprocessed_train_df['class_name'].unique())

# print the number of reports in each class
print(preprocessed_train_df['class_name'].value_counts())



5
['Backend' 'Frontend' 'Security' 'Documentation' 'Performance']
Backend          7437
Frontend         5799
Security          367
Documentation     174
Performance        89
Name: class_name, dtype: int64


In [31]:
# lets try topic modeling using LDA
from sklearn.decomposition import LatentDirichletAllocation

# Initialize the LDA model
lda = LatentDirichletAllocation(n_components=5, random_state=42)

# Fit the LDA model on the training data
lda.fit(X_train)

# Print the topics found by the LDA model
for i, topic in enumerate(lda.components_):
    print(f'Top 10 words for topic #{i}:')
    print([vectorizer.get_feature_names_out()[index] for index in topic.argsort()[-10:]])
    print('\n')



Top 10 words for topic #0:
['field', 'on', 'api', 'the', 'custom', 'to', 'issue', 'in', 'notification', 'email']


Top 10 words for topic #1:
['eclipse', 'java', 'on', 'not', 'with', 'for', 'in', 'to', 'error', 'project']


Top 10 words for topic #2:
['to', 'is', 'not', 'rest', 'user', 'for', 'issue', 'the', 'in', 'api']


Top 10 words for topic #3:
['bar', 'and', 'when', 'search', 'is', 'menu', 'to', 'in', 'the', 'tab']


Top 10 words for topic #4:
['redmine', 'user', 'email', 'of', 'notification', 'not', 'in', 'for', 'the', 'to']




In [36]:
# print each class and the number of reports in that class from class_name column
print(preprocessed_train_df['class_name'].value_counts())

Backend          7437
Frontend         5799
Security          367
Documentation     174
Performance        89
Name: class_name, dtype: int64


In [37]:
import numpy as np

# Replace NaN values with an empty string
preprocessed_test_df['bug_description'].fillna('', inplace=True)

# Transform the preprocessed test data
X_test = vectorizer.transform(preprocessed_test_df['bug_description'])

# Print the shape of the transformed test data
print("Shape of transformed test data:", X_test.shape)

# Predict the class of the test data
predictions = lda.transform(X_test)

# Print the shape of the predictions
print("Shape of predictions:", predictions.shape)

# Print the first prediction
print("First prediction:", predictions[0])

# Get the predicted class for each test report
predicted_class = [np.argmax(prediction) for prediction in predictions]

# Print the predicted class for the first test report
print("Predicted class for the first test report:", predicted_class[0])

# Print the first 5 predicted classes
print("First 5 predicted classes:", predicted_class[:5])

# Print the first 5 actual classes
print("First 5 actual classes:", preprocessed_test_df['class_name'][:5])


Shape of transformed test data: (2441, 7663)
Shape of predictions: (2441, 5)
First prediction: [0.05777235 0.77220967 0.05812538 0.05529076 0.05660184]
Predicted class for the first test report: 1
First 5 predicted classes: [1, 0, 3, 2, 4]
First 5 actual classes: 0     Backend
1    Frontend
2    Frontend
3     Backend
4     Backend
Name: class_name, dtype: object


In [38]:
# print each class and the number of reports in that class after training the model
print(preprocessed_test_df['class_name'].value_counts())

Backend          1345
Frontend          987
Security           70
Documentation      21
Performance        18
Name: class_name, dtype: int64


In [39]:
# print each class and the number of reports in that class
print(preprocessed_test_df['class_name'].value_counts())


Backend          1345
Frontend          987
Security           70
Documentation      21
Performance        18
Name: class_name, dtype: int64


In [40]:
# take a random test report and its predicted class
random_index = 11
print("Test report:", preprocessed_test_df['bug_description'][random_index])
print("Actual class:", preprocessed_test_df['class_name'][random_index])
print("Predicted class:", predicted_class[random_index])


Test report: when choosing a different application to open a file the chosen application is ignored
Actual class: Backend
Predicted class: 3


In [41]:
# Create a mapping between cluster labels and class names
cluster_class_mapping = {
    0: 'Backend',  # Example mapping, adjust based on your actual clusters
    3: 'Frontend',
    2: 'Security',
    1: 'Documentation',
    4: 'Performance'
}


In [42]:
from sklearn.metrics import classification_report, confusion_matrix

# Map numerical indices to class names
predicted_class_names = [cluster_class_mapping[label] for label in predicted_class]

# Print the classification report
print("Classification Report:")
print(classification_report(preprocessed_test_df['class_name'], predicted_class_names))

# Print the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(preprocessed_test_df['class_name'], predicted_class_names))

# Print the accuracy
accuracy = np.mean(preprocessed_test_df['class_name'] == predicted_class_names)
print("Accuracy:", accuracy)

# Print the precision
precision = np.mean([1 if actual == predicted else 0 for actual, predicted in zip(preprocessed_test_df['class_name'], predicted_class_names)])
print("Precision:", precision)

# Print the recall
recall = np.mean([1 if actual == predicted else 0 for actual, predicted in zip(preprocessed_test_df['class_name'], predicted_class_names)])
print("Recall:", recall)

# Print the F1 score
f1_score = 2 * (precision * recall) / (precision + recall)
print("F1 Score:", f1_score)



Classification Report:
               precision    recall  f1-score   support

      Backend       0.69      0.15      0.25      1345
Documentation       0.01      0.19      0.02        21
     Frontend       0.63      0.48      0.54       987
  Performance       0.01      0.17      0.01        18
     Security       0.03      0.24      0.06        70

     accuracy                           0.29      2441
    macro avg       0.27      0.25      0.18      2441
 weighted avg       0.64      0.29      0.36      2441

Confusion Matrix:
[[203 266 248 329 299]
 [  3   4   5   5   4]
 [ 80 144 469 132 162]
 [  4   4   3   3   4]
 [  4   7  23  19  17]]
Accuracy: 0.28512904547316675
Precision: 0.28512904547316675
Recall: 0.28512904547316675
F1 Score: 0.28512904547316675
